### ISSUE TITLE
Can't customize my own datacodec

### ISSUE THREAD

**Issue by newroot** [ronenhamias/scalecube-services#186]
From the source code, it seems "io.scalecube.services.annotations.ContentType" is not supported yet.

**Comment by artem-v** [comment]
@newroot what is expected behaviour for you when you are referring to _customize my own datacodec_ ? I imagine this is super-possible, but want to double check with you.

**Comment by bsideup** [comment]
I've also observed that `@ContentType` is simply ignored (at least with `.call().api(MyService.class)`-style.

P.S. Would be cool if `@ContentType` can be applied to both method argument and method's return type, to have different ones if needed. Oh, and also at class level, e.g. if I always exchange protobuf messages and not JSONs

**Comment by ronenhamias** [comment]
@bsideup yep at this point only one content type at a time is supported and the latest refactoring as part of version 2.0 opens the possiblity to support several endpoint content type at the same time.

one of the main leading ideas of this refactoring is not to decode data until it reach the last mile before service invoke. avoiding copy / GC pressure / and cpu so in case a message routes in the cluster it decode at the edges. and only service message header is decoded when needed.

in such case we also introduced the content type and a decoder that react to it.  the plan is to allow more endpoints for same service to run side by side and a service will stay agnostic to the content type it is provision with.

the idea is to allow also Aeron transport along side with netty transport.

the consumer will choose the contentType in which it wish to consume the service.

i am trying to think on a usescase where a consumer request a stream with json and accept it in protobuf and its not so trivial in my point of view.

to better understand your idea can you elaborate on a usecase where service consumer might work in such mix mode?

**Comment by ronenhamias** [comment]
@newroot please check out an example of another possible codec that was created to showcase how to provide alternative codec:
https://github.com/scalecube/scalecube-services/tree/develop/services-codec-protostuff

**Comment by artem-v** [comment]
Let's conclude basics:

* Caller's service message request may come on service node with contentType header inside; if it's not set then contentType is  assumed to be a JSON; we can't guess out of raw bytes what content type this is.

* Service implementors may define optional annotation `@ContentType` on class or (/and) a method; if annotation couldn't be found (neither on method nor on a class) then contentType value is assumed to be a `*/*`, i.e. it means service supports all available data formats defined at runtime (more on this later).

* If annotation is defined on a class as well as on the method then method declaration prevails. If found content type is not available from runtime (i.e. you simply forgotten to add corrsponding msg codec to classpath) then Microservices would fail to start. That has to be done to prevent service declaring that it supports certain content type but in fact it doesn't, let's fail fast.

* Upon `*/*` contentType which had been referenced above. This is a term to define `all avaliable content types that had been provided at classpath`, in short: this is msg codec jars which had been put in classpath.

* Content type must be exposed for service msg routing process; i.e. service messages must be routed with regards to the content type of the services.



Sequence of exposing content type on service node:

* Service method -> service class -> Microservices platform classpath; which means:

- if content type was defined on method (or on a service class) then it's cool but we need to check do we have corresp codec at runtime; if we found codec -> expose content type for this service, if not -> raise a fail.
- if content type was not defined at all neither on class nor on method, then it's just fine, we will look what msg codecs do we have at classpath,  collect content types they declare and expose that info for this service.

**Comment by ronenhamias** [comment]
the way i see it is that we drop in the codecs that user want to the class path by just including them to the maven.

when the microservices is loading it finds all the codecs in the class path and expose/provision the services for each codec found.

when service endpoint is provisioned we attach available content type to it in the discovery.

when consumer send a message and encode it using some specific or preferable content type he can choose how to encode the message and we look for such endpoint with such content type in the address list.

in case not found we get service not found.

about the idea of @ContentType annotation:

i think that service should remain careless about the specific of how its being consumed. service is just a method and maybe consumed in many ways and routes and it just provides the service.

its more matter of bootstrapping and configuration and less business of the actual service as service dont see transport and really dont mind.

i suggest to delete the @ContentType annotation from the project at this point and bring it back later when we will see conceivable usecase.
