### ISSUE TITLE
Are we still using ContentType annotaion?

### ISSUE THREAD

**Issue by aharonha** [ronenhamias/scalecube-services#45]
https://github.com/scalecube/scalecube-services/blob/sergeyr-support-tags/services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java#L34

https://github.com/scalecube/scalecube-services/blob/sergeyr-support-tags/services/src/main/java/io/scalecube/services/discovery/ServiceScanner.java#L40

**Comment by ronenhamias** [comment]
i suggest not to apply contentType on service annotation 
as service does not care about content type
service knows to answer on requests and does not care how transport deliver them
